[package]
name = "cairo-replay"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

resolver = "2"

[profile.release-lto]
inherits = "release"
codegen-units = 1
lto = true

[profile.dev.package.flate2]
opt-level = 3

[dependencies]
anyhow = "1.0.75"
cairo-lang-starknet-classes = { version = "=2.6.0" }
cairo-lang-runner = { version = "=2.6.0" }
cairo-lang-compiler = { version = "=2.6.0" }
cairo-lang-sierra = { version = "=2.6.0" }
cairo-lang-utils = { version = "=2.6.0" }
cairo-lang-sierra-generator = { version = "=2.6.0" }
jemallocator = "0.5.4"
pathfinder-common =  { git = "https://github.com/reilabs/pathfinder.git", rev = "eb90843ec0069eeef1f8e6e9b5af9fa15b68670b" }
pathfinder-executor =  { git = "https://github.com/reilabs/pathfinder.git", rev = "eb90843ec0069eeef1f8e6e9b5af9fa15b68670b" }
pathfinder-rpc =  { git = "https://github.com/reilabs/pathfinder.git", rev = "eb90843ec0069eeef1f8e6e9b5af9fa15b68670b" }
pathfinder-storage =  { git = "https://github.com/reilabs/pathfinder.git", rev = "eb90843ec0069eeef1f8e6e9b5af9fa15b68670b" }
rayon = "1.8.0"
starknet_api = "=0.10.0"
serde = "1.0.130"
serde_json = "1.0.81"
# blockifier = { path = "../blockifier/crates/blockifier" } #"=0.6.0-rc.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = [
    "env-filter",
    "time",
    "ansi",
] }
