[workspace]
resolver = "2"

members = [
    "cli",
    "cairo_replay"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/reilabs/cairo-replay"
keywords = ["cairo", "starknet"]
readme = "README.md"

[workspace.dependencies]
anyhow = "1.0.75"
cairo-lang-starknet-classes = "2.6.0"
cairo-lang-sierra-to-casm = "2.6.0"
cairo-lang-runner = "2.6.0"
cairo-lang-compiler = "2.6.0"
cairo-lang-sierra = "2.6.0"
cairo-lang-utils = "2.6.0"
cairo-lang-sierra-generator = "2.6.0"
jemallocator = "0.5.4"
pathfinder-common =  { git = "https://github.com/reilabs/pathfinder.git", rev = "5b95561e45da837cbfb579ede1e6a66358bd970f" }
pathfinder-executor =  { git = "https://github.com/reilabs/pathfinder.git", rev = "5b95561e45da837cbfb579ede1e6a66358bd970f" }
pathfinder-rpc =  { git = "https://github.com/reilabs/pathfinder.git", rev = "5b95561e45da837cbfb579ede1e6a66358bd970f" }
pathfinder-storage =  { git = "https://github.com/reilabs/pathfinder.git", rev = "5b95561e45da837cbfb579ede1e6a66358bd970f" }
rayon = "1.8.0"
starknet_api = "0.10.0"
serde = "1.0.130"
serde_json = "1.0.81"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = [
    "env-filter",
    "time",
    "ansi",
] }
smol_str = { version = "0.2.0", features = ["serde"] }
itertools = { version = "0.11.0", default-features = false }
