[workspace]
resolver = "2"

members = [
    "cli",
    "cairo_replay"
]

[workspace.package]
edition = "2021"
# Version chosen only because 1.78.0 is the stable version when writing this Cargo.toml
# If this version is changed, amend the version set in `build.yml`
rust-version = "1.78.0"
license = "Apache-2.0"
repository = "https://github.com/reilabs/cairo-replay"
keywords = ["cairo", "starknet"]
readme = "README.md"

# Prevent publishing by accident.
publish = false

[workspace.dependencies]
anyhow = "1.0.75"
# Hardcoding the commit hash until the changes to pathfinder are merged in the main branch of `eqlabs/pathfinder`
pathfinder-storage =  { git = "https://github.com/reilabs/pathfinder.git", rev = "82a749e6c0c2b88e1242cad202004bea165dcbd6" }
rayon = "1.8.0"
tracing = "0.1.37"
itertools = { version = "0.11.0", default-features = false }
