# Ensure this is matching `Cargo.toml`.
edition = "2021"

# Better readability
format_code_in_doc_comments = true
wrap_comments = true
format_strings = true

# Consistency
normalize_doc_attributes = true
use_field_init_shorthand = true
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"
imports_granularity = "Module"

# Wrapping
comment_width = 80
max_width = 100
