[package]
name = "starknet-replay"
version = "0.1.0"
description = "Back end to replay Starknet transactions and print histogram of libfuncs usage."
categories = ["cryptography::cryptocurrencies"]
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

# Prevent publishing by accident.
publish = false

[dependencies]
# All `cairo-lang-` crates must have the same version
cairo-lang-starknet-classes = "2.6.0"
cairo-lang-sierra-to-casm = "2.6.0"
cairo-lang-runner = "2.6.0"
cairo-lang-compiler = "2.6.0"
cairo-lang-sierra = "2.6.0"
cairo-lang-utils = "2.6.0"
cairo-lang-sierra-generator = "2.6.0"
# Some changes are required to `eqlabs/pathfinder` and to
# `starkware-libs/blockifier`. These changes are in the branch `extract_libfunc`
# of Reilabs fork and need to be merged in main branch.
# Hardcoding the commit hash for the time being.
pathfinder-common =  { git = "https://github.com/reilabs/pathfinder.git", rev = "fdeb5b0d1747d6396e5b0774140026a3b1beae2f" }
pathfinder-executor =  { git = "https://github.com/reilabs/pathfinder.git", rev = "fdeb5b0d1747d6396e5b0774140026a3b1beae2f" }
pathfinder-rpc =  { git = "https://github.com/reilabs/pathfinder.git", rev = "fdeb5b0d1747d6396e5b0774140026a3b1beae2f" }
pathfinder-storage =  { git = "https://github.com/reilabs/pathfinder.git", rev = "fdeb5b0d1747d6396e5b0774140026a3b1beae2f" }
# `plotters` is using the latest (as of 30-May-2024) commit on the branch
# `next-release-devel` because it contains the fix for bug #551 related to
# anchoring of labels when rotated. Issue #26.
plotters = { git = "https://github.com/plotters-rs/plotters.git", rev = "a7a3f8989af20931dd9e7e1f204d5254de3a8053" }
rayon = "1.8.0"
starknet_api = "0.10.0"
serde = "1.0.192"
serde_json = "1.0.105"
smol_str = { version = "0.2.0", features = ["serde"] }
thiserror = "1.0.61"
anyhow.workspace = true
tracing.workspace = true
itertools.workspace = true

[dev-dependencies]
indoc = "2.0.5"
rand = "0.8.4"
rand_chacha = "0.3.1"
