name: Push Checks
on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Rustup stable
      run: rustup toolchain install stable
    - name: Build
      run: cargo build
    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "rust-stable-cache"
    - name: Cargo fmt
      run: cargo fmt --all -- --check
    - name: Cargo clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test
