name: Push Checks
on: push

env:
  RUST_VERSION: 1.78.0
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "build-cache"
        cache-all-crates: "true"
        cache-directories: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
    - name: Build
      run: cargo build --locked
    - name: Run tests
      run: cargo test --locked

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "clippy-cache"
        cache-all-crates: "true"
        cache-directories: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
    - name: Cargo clippy
      run: cargo clippy --locked --all-targets --all-features -- -D warnings

  lint:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: "fmt-cache"
        cache-all-crates: "true"
        cache-directories: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
    - name: Install rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: rustfmt
    - name: Cargo fmt
      run: cargo +nightly fmt --all -- --check
